"CREATE TABLE Employee (
    GPN INTEGER PRIMARY KEY,
    FIRST_NAME TEXT NOT NULL,
    LAST_NAME TEXT NOT NULL,
    EMPLOYEE_LOCATION TEXT NOT NULL,
    COST_CENTRE TEXT NOT NULL,
    WORK_EXPERIENCE INTEGER NOT NULL,
    INTERESTED_IN_CHANGE BOOLEAN
);"
"CREATE TABLE SKILL_DETAILS (
    GPN INTEGER,
    SKILL_NAME TEXT NOT NULL,
    EXPERIENCE INTEGER NOT NULL,
    ACTIVE_SKILL BOOLEAN,
    FOREIGN KEY (GPN) REFERENCES Employee (GPN)
);"
"CREATE TABLE ASPIRATION (
    GPN INTEGER,
    INTERESTED_AREA TEXT NOT NULL,
    FOREIGN KEY (GPN) REFERENCES Employee (GPN)
);"

"CREATE TABLE JOB_DETAILS (
    JOB_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GPN INTEGER,
    JOB_TITLE TEXT NOT NULL,
    RANK TEXT NOT NULL,
    COST_CENTER TEXT NOT NULL,
    JOB_TYPE TEXT NOT NULL,
    JOB_LOCATION TEXT NOT NULL,
    JOB_DESCRIPTION TEXT NOT NULL,
    EXPERTISE TEXT NOT NULL,
    FOREIGN KEY (GPN) REFERENCES Employee (GPN)
);"
